### ISSUE TITLE
Enabling the allow-kernel-type-selection option breaks the kernels window

### ISSUE THREAD

**Issue by alankeny** [linuxmint/mintupdate#915]
**Describe the bug**
After upgrading Linux Mint from 22.0 to 22.1, the Linux Kernels window in Update Manager no longer opens while the allow-kernel-type-selection option is enabled.

**Screenshots**
Not applicable.

**To Reproduce**
1. Upgrade Linux Mint from 22.0 to 22.1.
2. In a terminal execute the command `dconf write /com/linuxmint/updates/allow-kernel-type-selection true`
3. Launch Update Manager
4. From the View menu, select the Linux Kernels option
5. Update Manager never opens the Kernels window

**Expected behavior**
The kernels window should open with the option to select a Kernel flavor from a pop-up menu in the lower left corner.

**Distribution:**
- [X] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
7.0.5

**Logs:**
Not applicable, please see crash reports.

**Crash report:**
First run:
```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1900, in on_kernel_menu_activated
    KernelWindow(self.on_kernel_window_closed)
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 227, in __init__
    self.kernel_type_combo.append_text(kernel_type[1:])
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KernelWindow' object has no attribute 'kernel_type_combo'. Did you mean: 'ui_kernel_type_combo'?
```

After making the suggested change, second run:
```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1900, in on_kernel_menu_activated
    KernelWindow(self.on_kernel_window_closed)
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 229, in __init__
    self.kernel_type_combo.set_active(index)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KernelWindow' object has no attribute 'kernel_type_combo'. Did you mean: 'ui_kernel_type_combo'?
```

After making the suggested change, third run:
```
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 1900, in on_kernel_menu_activated
    KernelWindow(self.on_kernel_window_closed)
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 230, in __init__
    self.ui_kernel_type_combo.connect("changed", on_kernel_type_combo_changed)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'on_kernel_type_combo_changed' is not defined. Did you mean: 'self.on_kernel_type_combo_changed'?
```

**Additional context**
After making all three suggested changes, the Kernel window opens and displays the Kernel flavor pop-up menu as expected.  I can't speak to the quality of the changes suggested, other than the window opens.

**Locale:**
Not applicable.

[kernelwindow.py.txt](https://github.com/user-attachments/files/18469585/kernelwindow.py.txt)

**Comment by Wohlstand** [comment]
I found the same bug on my end after fresh installation. Actually it's easy to fix. Let me prepare the patch...

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/mintupdate/pull/922
